#ifndef __HAILO_1X_PRODUCT_H
#define __HAILO_1X_PRODUCT_H

#include <include/dt-bindings/soc/hailo15_scmi_api.h>

#define HAILO_PRODUCT_ID__INVALID HAILO_SCMI_PRODUCT_ID__INVALID
#define HAILO_PRODUCT_ID__15H HAILO_SCMI_PRODUCT_ID__15H
#define HAILO_PRODUCT_ID__15M HAILO_SCMI_PRODUCT_ID__15M
#define HAILO_PRODUCT_ID__15L HAILO_SCMI_PRODUCT_ID__15L
#define HAILO_PRODUCT_ID__10H HAILO_SCMI_PRODUCT_ID__10H
#define HAILO_PRODUCT_ID__12L HAILO_SCMI_PRODUCT_ID__12L

#endif /* __HAILO_1X_PRODUCT_H */